name: Post-Deploy Health Check

on:
  workflow_run:
    workflows: ["CI/CD Deploy to EC2"]
    types:
      - completed

jobs:
  check-health:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Ping EC2 App
        run: |
          curl -s --fail http://${{ secrets.EC2_PUBLIC_IP }}:3000 || exit 1
